### ISSUE TITLE
Cannot find `Upload` to press

### ISSUE THREAD

**Issue by chengtie** [OfficeDev/Office-OOXML-EmbedAddin#1]
Hello,

I'm trying to run this project on my machine. I just added a `test.xlsx` in the folder, and pressing F5 opened a browser as follows:

![screenshot 2019-02-28 at 12 42 24](https://user-images.githubusercontent.com/774409/53564170-7ce32d00-3b56-11e9-9cc5-e000343e30c6.png)

From the readme, I should `Use the Browse control on the page to navigate to any Excel, Word, or PowerPoint file` and `Press Upload`, but where is `Upload`?

Could anyone help?

Cheers

Tie

**Comment by Rick-Kirkham** [comment]
@chengtie It should open home.aspx, not the parent folder. I'll see if I can reproduce, but it might be a few days before I get the chance.

**Comment by chengtie** [comment]
Hello,

By clicking on `home.aspx`, I do see the upload page.

Cheers

Tie

**Comment by Rick-Kirkham** [comment]
I can reproduce this on Visual Studio 2019 Preview. Apparently, there's been a change in VS default behavior since the sample was created. You now have to take the following steps before you press F5:
Right-click the project in Solution Explorer and select Properties. 
When the Properties pane opens, open the Web tab.
On the Web tab, enable Specific Page and enter Home.aspx in the text box. 
I will add this to the Readme.
